version: "3.9"

services: 
  db:
    image: mysql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: userdatavalidation
      MYSQL_ROOT_PASSWORD: mjs
      MYSQL_ROOT_PASSWORD: mjs
      MYSQL_TCP_PORT: 3306
      # MYSQL_ROOT_HOST:  %
    expose: 
      - "3306"
  
  web:
    build: .
    # command: python manage.py runserver 127.0.0.1:8000
    command: python manage.py makemigrations 
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/UserValidation
    ports: 
      - "8000:8000"
    depends_on: 
      - db
